name: Edwise workflow
on:
    workflow_dispatch: # Allows manual triggering of the workflow

jobs:
    test:
        permissions:
            contents: read
            pages: write
            id-token: write
        runs-on: ubuntu-latest
        name: UI tests
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20
                  cache: npm

            - name: Install Dependencies
              run: npm install

            - name: Create JSON Reports Directory
              run: mkdir -p test/.artifacts/json-reports

            - name: Execute Tests
              run: npm run wdio

            - name: Install Allure CommandLine
              if: always()
              run: npm install -g allure-commandline

            - name: Generate Allure Report
              if: always()
              run: npm run allureCombine

            - name: Upload Allure Test Report
              if: always()
              uses: actions/upload-artifact@v3
              with:
                  name: Allure Report
                  path: test/.artifacts/allure-report # Adjust path if needed
